server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.7:1111 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'