server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #使用注册中心的服务名路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #使用注册中心的服务名路由地址
          filters:
            #- AddRequestParameter=username,1 # 过滤器工厂会在匹配的请求头加上一对请求头，名称为 X-Request-Id 值为 1024
            - Pre=name # 自定义的局部过滤器使用方式
          predicates: # 该属性包含多种默认方法来将 Predicate 组合成其他复杂的逻辑 ( 比如：与，或，非 )
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=age, \d+  # 请求头要有age属性并且值为整数的正则表达式
            #- Host=**.baidu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名 username 并且值还要是整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka